version: '3.8'

services:
  web:
    build: .
    container_name: radiobox_web
    restart: always
    expose:
      - "5000"
    environment:
      - TZ=Europe/Kyiv
    volumes:
      - ./radiobox.db:/app/radiobox.db
      - ./assets/products:/app/assets/products
      - ./assets/banners:/app/assets/banners
      - ./backups:/app/backups
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: radiobox_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443" # Добавили порт HTTPS
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt # Даем Nginx доступ к сертификатам
    depends_on:
      - web