version: '3.8'

services:
  web:
    build: .
    container_name: radiobox_web
    restart: always
    expose:
      - "5000"
    volumes:
      - ./radiobox.db:/app/radiobox.db
      - ./assets/products:/app/assets/products
      - ./assets/banners:/app/assets/banners
      - ./backups:/app/backups
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: radiobox_nginx
    restart: always
    ports:
      - "80:80" # А вот Nginx будет смотреть в интернет и встречать посетителей
    volumes:
      - ./nginx:/etc/nginx/conf.d # Пробрасываем папку с конфигом, которую ты только что создал
    depends_on:
      - web # Nginx запустится только после того, как запустится твой Python-сервер