server {
    listen 80;
    # ОБЯЗАТЕЛЬНО: замени эти домены на тот, который ты купил на imena.ua!
    server_name radio-box.com.ua www.radio-box.com.ua;

    location / {
        # Здесь мы ссылаемся на твой контейнер, который в docker-compose называется 'web'
        proxy_pass http://web:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}