# Этот блок ловит обычные запросы (HTTP) и принудительно перекидывает их на HTTPS
server {
    listen 80;
    server_name radio-box.com.ua www.radio-box.com.ua;
    return 301 https://$host$request_uri;
}

# Этот блок обрабатывает защищенные запросы (HTTPS)
server {
    listen 443 ssl;
    server_name radio-box.com.ua www.radio-box.com.ua;

    # Увеличиваем лимит загрузки файлов до 10 МБ
    client_max_body_size 10M;

    # Пути к сертификатам
    ssl_certificate /etc/letsencrypt/live/radio-box.com.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/radio-box.com.ua/privkey.pem;

    location / {

        # === ИСПРАВЛЕНИЕ 404 ОШИБКИ ДЛЯ ПАПОК ===
        # Если запрашивают просто /ua/ или /ua, перенаправляем запрос на /ua/index.html
        rewrite ^/ua/?$ /ua/index.html break;
        # Аналогично для /ru/
        rewrite ^/ru/?$ /ru/index.html break;

        proxy_pass http://web:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;

        # === НАСТРОЙКИ ДЛЯ WEBSOCKETS (ЧАТ) ===
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        # Таймауты, чтобы Nginx не рвал неактивные соединения чата (1 час)
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}